### ISSUE TITLE
Send to t2i/i2i doesn't work

### ISSUE THREAD

**Issue by Aghneel** [jtydhr88/sd-3dmodel-loader#1]
Thank you for this great extension! 
When i try to send t2i/i2i it doesn't work, it freezes the page then redirected to t2i, that's it! 
I used Firefox/Chrome latest version windows 11, i have the multi controlnet activated, probably this is the cause.

**Comment by jtydhr88** [comment]
oh, I only have one controlnet, I will add more to try your case, thanks for the feedback!

**Comment by jtydhr88** [comment]
@Aghneel I add the support of multi controlnet here https://github.com/jtydhr88/sd-3dmodel-loader/commit/87d967d161826b55b0c120c21b0f8f45e4d1cac9, please let me know the problem still exist.
I will close this issue for now, you can reopen if the problem still exist. thanks for your feedback!

**Comment by aetherwu** [comment]
I encounter this issue too.
The image in ControlNet appears nothing changed after I clicked sendto i2i or t2i, neither single or multi ControlNet.
No error response.

On the other hand, I couldn't models from https://www.mixamo.com/.

**Comment by jtydhr88** [comment]
hi @aetherwu , it may cause by different ControlNet version. Currently, I am using 1031a902 (Fri Mar 3 02:56:49 2023) for ControlNet, and will update it to later and double check the issue exists or not on this later version, thanks for feedback!

**Comment by jtydhr88** [comment]
@aetherwu I updated ControlNet to latest **c9340671 (Sat Mar 11 01:01:43 2023)**, and the features work well on my side, so can you try to update as well?
