### ISSUE TITLE
Unusual CPU load even when not being ative

### ISSUE THREAD

**Issue by justanothernguyen** [jtydhr88/sd-3dmodel-loader#12]
I'm guessing that the extension is making too much fps. On blank state if I uncheck "Show ground" the CPU load immediately drop (will not work if a model is already loaded).

I think there should be a low-fps mode, and there should be detection if "3D Model Loader" is the active tab - if it's not then no frame should be rendered at all.

**Comment by TerryJia** [comment]
Good catch, Gradio will load all resources of all extension on the top, which means, yes, even not on this tab, it is still running “background”.
However, this should be an issue and should get fixed, I will take a look at it and figure out how to fix. Thanks for feedback!

**Comment by jtydhr88** [comment]
hi @justanothernguyen I made an improvement here https://github.com/jtydhr88/sd-3dmodel-loader/commit/9d118582a23c22c23ef7533eede697866895b31f, please let me know the performance get improved or not, thanks for your help!

**Comment by jtydhr88** [comment]
close this issue for now

**Comment by justanothernguyen** [comment]
Thanks for prompt response @jtydhr88, the performance is indeed better now.
