### ISSUE TITLE
Is there possible line art mode?

### ISSUE THREAD

**Issue by sanmeow** [jtydhr88/sd-3dmodel-loader#19]
Hello! Thanks to your great extention!
I have question, 
can there be a line art mode?Similar to this below. It well be very nice for scribble mode and canny mode in control net.
https://minux302.github.io/haikei_assistant/

(Some more information)
https://github.com/minux302/haikei_assistant
https://github.com/gkjohnson/threejs-sandbox/tree/master/conditional-lines

Keep the good work!

I have also make a ZoeDepth extention export GLB file from image. Making 3D in diffusion more easier ways to transfer from image.Still try to figure out how to export color OBJ file for python and reduce VRAM usage,work in process for now.

https://github.com/sanmeow/a1111-sd-zoe-depth

**Comment by sanmeow** [comment]
Glad to know! Looking forward to it!

**Comment by jtydhr88** [comment]
implemented here https://github.com/jtydhr88/sd-webui-3d-editor, close this issue
