### ISSUE TITLE
Can't load fbx format

### ISSUE THREAD

**Issue by Aghneel** [jtydhr88/sd-3dmodel-loader#2]
I tried to load fbx format but it doesnt show up, the obj format works fine tho.

**Comment by jtydhr88** [comment]
hi @Aghneel, the problem may be the model is too "small", I consider to add scale option on the page. I will let me know you when I add it.

**Comment by Aghneel** [comment]
Actually my model contained tga files, and it was way too big i couldnt see it haha, thanks
