### ISSUE TITLE
animation controls

### ISSUE THREAD

**Issue by jtydhr88** [jtydhr88/sd-3dmodel-loader#23]
currently, it only has play/pause/stop for FBX animation controls, but it should have more, like:
1. progress bar (done)
2. update progress bar while playing
3. animation select

**Comment by angeldart** [comment]
I have a problem, I press send to Img2Img and do nothing

**Comment by chucktobbes** [comment]
I imagine a feature to export the individual frames of the animation in single images all at once with a frame rate option via a batch process button to use them for example in img2img in batch processing

**Comment by angeldart** [comment]
@jtydhr88 yeah I have installed control net but the send to img2img, switch the tab to img2img but dont "paste" the image.

**Comment by angeldart** [comment]
@chucktobbes its not impossible, alredy exist scripts that use ffmpeg codec to convert a png sequence from a folder to mp4, gif and loopable mp4. I already use one for that. Its not crazy another script that uses the same process but inverse. Also should be could that the 3d model loader admit texrures, at least albedo because fbx and gbtl already have embebed textures but just load vertex color data

**Comment by angeldart** [comment]
I would like to learn more about to do this kind of extensions or tools. Me as 3D modem could release or add lots of features. But I think its more essy think about that really code this things.

**Comment by chucktobbes** [comment]
Now I got the same bug as @angeldart, after pressing the button it switches to the correct tab, but doesn't paste the image. It worked before in both txt2img and img2img with multiple control-net models, but currently it won't work anymore. I also tried to check out some earlier commits for both extensions, but didn't get to work anymore.

**Comment by chucktobbes** [comment]
This is interesting, I am using the same commits for model-loader and openpose and its still not working ... here are my extensions ... I am using Firefox btw

![grafik](https://user-images.githubusercontent.com/77232175/227784011-36508972-c948-4ef3-9bb0-0c84fb7aa443.png)

**Comment by chucktobbes** [comment]
yes there are errors 
![grafik](https://user-images.githubusercontent.com/77232175/227786584-f2a4b1f2-6ec5-413c-a055-07a6a9cd0d8f.png)

**Comment by chucktobbes** [comment]
that wasn't it same error on the same line within the new commit

**Comment by chucktobbes** [comment]
@jtydhr88 we can talk on discord if you want

**Comment by chucktobbes** [comment]
@jtydhr88 I can only see the same errors in same the lines ... did I need to do something else than "check for updates" and "apply and restart UI"?

**Comment by chucktobbes** [comment]
yes now I get different errors

Uncaught (in promise) TypeError: v is undefined
    ct Blocks.5efe22d4.js:76
    ze Blocks.5efe22d4.js:76
    promise callback*ze Blocks.5efe22d4.js:76
    to Blocks.5efe22d4.js:76
    zr index.37b24c07.js:4
    zr index.37b24c07.js:4
    _ Button.svelte:12
    zr index.37b24c07.js:4
    zr index.37b24c07.js:4
    c Button.svelte:11
Blocks.svelte:214:2
Uncaught TypeError: element is undefined
    updateGradioImage 3d-model-loader.js:908
    sendImage 3d-model-loader.js:903
    sendImage 3d-model-loader.js:867
    sendImage3DModel 3d-model-loader-webui.js:75
    result Blocks.5efe22d4.js line 75 > AsyncFunction:3
    anonymous Blocks.5efe22d4.js line 75 > AsyncFunction:3
    ze Blocks.5efe22d4.js:76
    to Blocks.5efe22d4.js:76
    zr index.37b24c07.js:4
    zr index.37b24c07.js:4
    _ Button.svelte:12
    zr index.37b24c07.js:4
    zr index.37b24c07.js:4
    c Button.svelte:11
3d-model-loader.js:908:23
    updateGradioImage 3d-model-loader.js:908
    sendImage 3d-model-loader.js:903
    (Async: BlobCallback)
    sendImage 3d-model-loader.js:867
    sendImage3DModel 3d-model-loader-webui.js:75
    result Blocks.5efe22d4.js line 75 > AsyncFunction:3
    anonymous Blocks.5efe22d4.js line 75 > AsyncFunction:3
    ze Blocks.svelte:283
    to Blocks.svelte:342
    zr index.37b24c07.js:4
    forEach self-hosted:203
    zr index.37b24c07.js:4
    _ Button.svelte:12
    zr index.37b24c07.js:4
    forEach self-hosted:203
    zr index.37b24c07.js:4
    c Button.svelte:11
