### ISSUE TITLE
Make the settings dynamic 

### ISSUE THREAD

**Issue by Aghneel** [jtydhr88/sd-3dmodel-loader#3]
Without reloading, and maybe no need to go to the settings to change them each time 👍

**Comment by jtydhr88** [comment]
Yes, I also find it is better without reloading, this is my next feature plan! thanks!

**Comment by jtydhr88** [comment]
@Aghneel I add the configuration on page https://github.com/jtydhr88/sd-3dmodel-loader/commit/6a1014bcd7ce792212c7e172a7122dff4c44a78b
![image](https://user-images.githubusercontent.com/860985/224429819-26a040fb-77e7-4a08-b52c-7e848bf39328.png)
looking forward your more feedback!

**Comment by Aghneel** [comment]
Works like a charm! Thanks for the great work, looking forward to new features!
