### ISSUE TITLE
redesign UI

### ISSUE THREAD

**Issue by jtydhr88** [jtydhr88/sd-3dmodel-loader#43]
extension 3D Openopen has a nice UI which inspired me to redesign the UI of this extension
![image](https://user-images.githubusercontent.com/860985/232232333-a5f53dca-3b56-422f-a216-68ec8bc6fc23.png)

**Comment by Pandelii** [comment]
As part of that redesign, or even perhaps separate from, adding the ability to change the FOV for the camera would be a great touch.
