### ISSUE TITLE
add Pose support back

### ISSUE THREAD

**Issue by jtydhr88** [jtydhr88/sd-3dmodel-loader#48]
I just finish refactor and not add pose editor back, will add back later

**Comment by kohweiteck** [comment]
Ah... I just wanted to open up an issue why the pose editor gone. Anyway thank you for your notifications and bless you on your hard work.

**Comment by TerryJia** [comment]
Hi @kohweiteck , since I rewrote this extension by Racat recently and I plan to redesign the pose editor more friendly, like edit pose from scene directly, just like what we do in blenld, c4d…
please give me some time to implement. Pretty sorry for inconvenience!

**Comment by kohweiteck** [comment]
> Hi @kohweiteck , since I rewrote this extension by Racat recently and I plan to redesign the pose editor more friendly, like edit pose from scene directly, just like what we do in blenld, c4d… please give me some time to implement. Pretty sorry for inconvenience!

No worries. Understand it will be huge undertaking. Just a suggestion to make it better. Preferably when scrolling up and down, the preview frame should be "locked" to see the effects of rotations in real time. Based on previous versions, if you open up too much of the tabs (Hands, Legs, Body,etc..) , the preview will be gone from view if user scroll down to bottom .
