### ISSUE TITLE
Two Types of DAE models

### ISSUE THREAD

**Issue by Piscabo** [jtydhr88/sd-3dmodel-loader#57]
Hi, I can export 2 types of DAE from Archicad 26
Colada Lumion - this one places the model under the modeling plane, I think I can see stuff there?
Colada Archicad - This one closes the interface to a black screen
I attach the 2 file types.
It worked fine a while back. Tried with your current version today, but no luck.
[DAETestModel.zip](https://github.com/jtydhr88/sd-3dmodel-loader/files/11514870/DAETestModel.zip)

Thank you for always updating this repository.

**Comment by jtydhr88** [comment]
pretty sorry to fix so delay (I am working on some another extension last month).
Sent a fix for this issue, I think right now it is back to good
![image](https://github.com/jtydhr88/sd-3dmodel-loader/assets/860985/a8832849-5eaa-454f-82d5-311c59092981)
