### ISSUE TITLE
Can't select new joint "through" rotation rings

### ISSUE THREAD

**Issue by Targren** [jtydhr88/sd-3dmodel-loader#61]
When a joint is already selected in "Rotate" mode, mousing over a new joint within the rendered rotation rings will highlight the new joint, but clicking it doesn't change the selected joint. In compressed poses where all joints are covered, the only way seems to be changing "Operate" to "None," selecting the new joint, and changing the operation to back to "Rotate"

**Comment by jtydhr88** [comment]
thanks for reporting this issue, it would be fixed in next commit

**Comment by jtydhr88** [comment]
fixed
