### ISSUE TITLE
Doesn't import its own exported pose JSON? 

### ISSUE THREAD

**Issue by Targren** [jtydhr88/sd-3dmodel-loader#62]
After exporting a pose, trying to import it either doesn't do anything, or it loads something that definitely isn't the saved pose, like collapsing the model into a JRPG slime monster (see attached pose files). 

1.  Load Y-BOT model 
2. Adjust model away from default T-Pose in some simple but clearly visible way (Arms over head, e.g.)
3. Click "Export Pose JSON" under "Body"
4. Remove Body model and add Y-Bot back in
5. Import the just-exported pose file
[poses.zip](https://github.com/jtydhr88/sd-3dmodel-loader/files/12576977/poses.zip)

**Comment by jtydhr88** [comment]
thanks for reporting the issue, I tested and found the issue happens on Vanguard and Y -Bot, and works fine on Kachujin and Warrok, I will try to fix it soon

**Comment by jtydhr88** [comment]
fixed
