### ISSUE TITLE
Y axis movement

### ISSUE THREAD

**Issue by AlexanderLJX** [jtydhr88/sd-3dmodel-loader#9]
How do I move on the Y axis? 

It seems like I can only move on the Z and X axis

**Comment by jtydhr88** [comment]
hi @AlexanderLJX, can I image Y axis mean **up and down**? you can use Mouse Left Button to rotate the camera for now. 
I will add the buttons of horizontal and vertical movement later.

**Comment by jtydhr88** [comment]
fix in https://github.com/jtydhr88/sd-3dmodel-loader/commit/71213fd1208c5ff7cf5358811ac67bcbbad15b52

**Comment by jtydhr88** [comment]
use https://github.com/jtydhr88/sd-3dmodel-loader/pull/11 instead

**Comment by jtydhr88** [comment]
After I updated threejs to R148, the feature https://github.com/jtydhr88/sd-3dmodel-loader/pull/11 broken, which needs to fix, reopen this issue.

**Comment by jtydhr88** [comment]
ignore me...
on this version, mouse right button can move Y-axis already.
Close again.
